# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://choihywook.github.io/
baseurl: /sustain/
title: Blog of Everything and Anything
author: Hyung Wook Choi
description: Explorer pushing my boundaries
avatar: profile.png
email: shinywook92@gmail.com
github: jekyller/sustain # username
#twitter: username
linkedin: username
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
